/**
 * Determines if a data type should be right-aligned (typically numeric types)
 */
export function isNumericDataType(dataType: string): boolean {
  const normalized = dataType.toLowerCase().trim();

  const numericTypes = [
    "int2",
    "int4",
    "int8",
    "integer",
    "smallint",
    "bigint",
    "numeric",
    "decimal",
    "real",
    "double precision",
    "double",
    "float",
    "money",
  ];

  return numericTypes.some((type) => normalized === type || normalized.includes(type));
}

/**
 * Determines if a data type is a date/time type
 * Date/time types should NOT be treated as relationships
 */
export function isDateTimeDataType(dataType: string): boolean {
  const normalized = dataType.toLowerCase().trim();

  const dateTimeTypes = [
    "date",
    "time",
    "timestamp",
    "timestamp without time zone",
    "timestamp with time zone",
    "timestamptz",
    "datetime",
    "datetime2",
  ];

  return dateTimeTypes.some((type) => normalized === type || normalized.startsWith(type));
}

/**
 * Client-side "now" value shaped for date/time form inputs.
 * date → YYYY-MM-DD; time → HH:mm:ss; timestamp/datetime → YYYY-MM-DDTHH:mm
 */
export function nowValueForDataType(dataType: string, now = new Date()): string {
  const normalized = dataType.toLowerCase().trim();
  const yyyy = now.getFullYear();
  const mm = pad2(now.getMonth() + 1);
  const dd = pad2(now.getDate());
  const hh = pad2(now.getHours());
  const mi = pad2(now.getMinutes());
  const ss = pad2(now.getSeconds());

  const isDateOnly =
    normalized === "date" ||
    (normalized.includes("date") &&
      !normalized.includes("time") &&
      !normalized.includes("timestamp"));
  if (isDateOnly) {
    return `${yyyy}-${mm}-${dd}`;
  }

  if (normalized === "time" || normalized.startsWith("time ")) {
    return `${hh}:${mi}:${ss}`;
  }

  return `${yyyy}-${mm}-${dd}T${hh}:${mi}`;
}

function pad2(n: number): string {
  return String(n).padStart(2, "0");
}

/**
 * Determines if a data type is boolean
 */
export function isBooleanDataType(dataType: string): boolean {
  const normalized = dataType.toLowerCase().trim();
  return (
    normalized === "boolean" ||
    normalized === "bool" ||
    normalized === "bit" ||
    normalized.startsWith("tinyint(1)")
  );
}

/**
 * Determines if a data type is JSON/JSONB
 */
export function isJsonDataType(dataType: string): boolean {
  const normalized = dataType.toLowerCase().trim();
  return normalized === "json" || normalized === "jsonb";
}

/**
 * Whether column metadata describes a PG enum with selectable values.
 */
export function isEnumColumn(column: { isEnum?: boolean; enumValues?: string[] | null }): boolean {
  return Boolean(column.isEnum && column.enumValues && column.enumValues.length > 0);
}

/**
 * Determines if a column is likely auto-generated (serial/identity/autoincrement)
 */
export function isAutoGeneratedColumn(dataType: string, defaultValue: string | null): boolean {
  const normalizedType = dataType.toLowerCase().trim();
  const normalizedDefault = defaultValue?.toLowerCase().trim() ?? "";

  if (
    normalizedType.includes("serial") ||
    normalizedType === "bigserial" ||
    normalizedType === "smallserial"
  ) {
    return true;
  }

  if (
    normalizedDefault.includes("nextval(") ||
    normalizedDefault.includes("autoincrement") ||
    normalizedDefault === "auto_increment"
  ) {
    return true;
  }

  return false;
}

/**
 * Determines the text alignment for a column based on its data type
 */
export function getColumnTextAlignment(dataType: string): "left" | "right" {
  return isNumericDataType(dataType) ? "right" : "left";
}

/**
 * Coerce a form/editor value into a SQL parameter for the given column type.
 * Pass `null` explicitly for SQL NULL.
 */
export function coerceColumnValue(dataType: string, value: unknown): unknown {
  if (value === null || value === undefined) {
    return null;
  }

  if (isBooleanDataType(dataType)) {
    if (typeof value === "boolean") return value;
    if (value === "true" || value === "t" || value === "1" || value === 1) return true;
    if (value === "false" || value === "f" || value === "0" || value === 0) return false;
    return Boolean(value);
  }

  if (isNumericDataType(dataType)) {
    if (typeof value === "number") return value;
    if (typeof value === "string" && value.trim() === "") return null;
    const num = Number(value);
    return Number.isFinite(num) ? num : value;
  }

  if (isJsonDataType(dataType)) {
    if (typeof value === "string") {
      const trimmed = value.trim();
      if (trimmed === "") return null;
      return trimmed;
    }
    return JSON.stringify(value);
  }

  if (isDateTimeDataType(dataType)) {
    if (value instanceof Date) return value.toISOString();
    return value;
  }

  return value;
}
