import type { TableColumnMetadata } from "#src/server/introspection/introspection.ts";

import { isAutoGeneratedColumn } from "#src/lib/data-type-utils.ts";

export interface InsertValuesSnippet {
  label: string;
  detail: string;
  insertText: string;
}

const quoteIdent = (name: string): string => `"${name.replace(/"/g, '""')}"`;

const placeholderForColumn = (col: TableColumnMetadata): string => {
  if (col.defaultValue != null) return "DEFAULT";
  if (col.nullable) return "NULL";
  const type = col.dataType.toLowerCase();
  if (
    type.includes("int") ||
    type.includes("numeric") ||
    type.includes("decimal") ||
    type.includes("real") ||
    type.includes("double") ||
    type.includes("float") ||
    type.includes("money")
  ) {
    return "0";
  }
  if (type === "boolean" || type === "bool" || type === "bit") {
    return "FALSE";
  }
  return "''";
};

/**
 * Build `(col1, col2) VALUES (...)` from column metadata.
 * Skips auto-generated serial/identity columns.
 */
export const buildInsertValuesSnippet = (
  columns: TableColumnMetadata[],
): InsertValuesSnippet | null => {
  const insertable = columns.filter(
    (col) => !isAutoGeneratedColumn(col.dataType, col.defaultValue ?? null),
  );
  if (insertable.length === 0) return null;

  const colList = insertable.map((c) => quoteIdent(c.name)).join(", ");
  const values = insertable.map(placeholderForColumn).join(", ");

  return {
    label: "(columns) VALUES (...)",
    detail: `Insert ${insertable.length} column${insertable.length === 1 ? "" : "s"}`,
    insertText: `(${colList}) VALUES (${values})`,
  };
};

/** True when the cursor is completing a table name after INTO. */
export const isAfterIntoKeyword = (beforeCursor: string): boolean => {
  return /\bINTO\s+(?:"[^"]*"|\w*)$/i.test(beforeCursor);
};

/** True when the cursor sits after `INTO table ` (ready for columns/VALUES). */
export const isAfterInsertIntoTable = (beforeCursor: string): boolean => {
  return /\bINTO\s+(?:"[^"]+"\.)?(?:"[^"]+"|\w+)(?:\s+AS\s+\w+)?\s+$/i.test(beforeCursor);
};
