packages:
  - .
  - packages/*
  - sandbox/**

autoInstallPeers: true

catalog:
  "@effect/experimental": 0.61.0
  "@effect/language-service": 0.87.0
  "@effect/opentelemetry": 0.64.0
  "@effect/platform": 0.97.0
  "@effect/platform-browser": 0.77.0
  "@effect/platform-node": 0.108.0
  "@effect/rpc": 0.76.0
  "@effect/sql": 0.52.0
  "@effect/sql-kysely": 0.48.0
  "@effect/sql-libsql": 0.42.0
  "@effect/sql-mysql2": 0.53.0
  "@effect/sql-pg": 0.53.0
  "@effect/sql-sqlite-node": 0.53.0
  "@effect/vitest": 0.30.0
  "@effect/workflow": 0.19.0
  "@electric-sql/pglite": 0.5.4
  "@electric-sql/pglite-tools": 0.4.4
  drizzle-orm: 0.45.2
  effect: 3.22.0

enableGlobalVirtualStore: false

enablePrePostScripts: true

ignoreWorkspaceRootCheck: true

injectWorkspacePackages: false

linkWorkspacePackages: true

preferWorkspacePackages: true

resolvePeersFromWorkspaceRoot: true

strictPeerDependencies: false
