import type { TableColumnMetadata } from "#src/server/introspection/introspection.ts";

import { Button } from "#src/components/ui/button.tsx";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
} from "#src/components/ui/sheet.tsx";
import { Tabs, TabsList, TabsTrigger } from "#src/components/ui/tabs.tsx";
import { toaster } from "#src/components/ui/toaster.tsx";
import { isAutoGeneratedColumn } from "#src/lib/data-type-utils.ts";
import { formatDbError } from "#src/lib/format-db-error.ts";
import { invalidateRowsQueries, rowMutationMeta } from "#src/lib/invalidate-rows-queries.ts";
import { insertRowServerFn } from "#src/server/introspection/start-fns/insert-row.start.ts";
import { updateRowServerFn } from "#src/server/introspection/start-fns/update-row.start.ts";
import { useForm } from "@tanstack/react-form";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";

import { ColumnInput } from "./column-input.tsx";
import { JsonMonacoEditor } from "./json-monaco-editor.tsx";
import { previewInsertSql, previewUpdateSql } from "./preview-sql.ts";
import {
  buildInitialRowValues,
  getEditableColumns,
  hasPrimaryKey,
  prepareSubmitValues,
  type RowEditorMode,
} from "./row-editor-values.ts";

export interface RowEditorSheetState {
  open: boolean;
  mode: RowEditorMode;
  row?: Record<string, unknown> | null;
}

export interface RowEditorSheetProps {
  open: boolean;
  mode: RowEditorMode;
  row?: Record<string, unknown> | null;
  connectionUrl: string;
  schema: string;
  table: string;
  columnMetadata: Array<TableColumnMetadata>;
  onOpenChange: (open: boolean) => void;
}

type EditorViewMode = "form" | "json";

function rowValuesToJsonText(values: Record<string, unknown>): string {
  const cleaned: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(values)) {
    if (value === undefined) continue;
    cleaned[key] = value;
  }
  return JSON.stringify(cleaned, null, 2);
}

function parseRowJsonText(
  text: string,
  editableColumns: ReadonlyArray<TableColumnMetadata>,
): Record<string, unknown> {
  const parsed: unknown = JSON.parse(text);
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new Error("JSON must be an object of column values");
  }
  const source = parsed as Record<string, unknown>;
  const next: Record<string, unknown> = {};
  for (const column of editableColumns) {
    next[column.name] = Object.hasOwn(source, column.name) ? source[column.name] : undefined;
  }
  return next;
}

export function RowEditorSheet(props: RowEditorSheetProps) {
  const { open, mode, row, connectionUrl, schema, table, columnMetadata, onOpenChange } = props;

  const queryClient = useQueryClient();
  const [showSql, setShowSql] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<EditorViewMode>("form");
  const [jsonText, setJsonText] = useState("");
  const [jsonError, setJsonError] = useState<string | null>(null);
  const formKey = `${mode}:${table}:${row ? JSON.stringify(Object.keys(row)) : "new"}:${open}`;

  const initialValues = useMemo(
    () => buildInitialRowValues(mode, columnMetadata, row),
    [mode, columnMetadata, row],
  );

  const editableColumns = useMemo(
    () => getEditableColumns(mode, columnMetadata),
    [mode, columnMetadata],
  );

  const canEdit = mode === "insert" || mode === "duplicate" || hasPrimaryKey(columnMetadata);

  const form = useForm({
    defaultValues: initialValues,
  });

  // Reset form when sheet opens with new data
  useEffect(() => {
    if (open) {
      form.reset(initialValues);
      setShowSql(false);
      setSubmitError(null);
      setViewMode("form");
      setJsonText(rowValuesToJsonText(initialValues));
      setJsonError(null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- reset only on open/mode/row change
  }, [open, formKey]);

  const switchViewMode = (next: EditorViewMode) => {
    if (next === viewMode) return;

    if (next === "json") {
      setJsonText(rowValuesToJsonText(form.state.values));
      setJsonError(null);
      setViewMode("json");
      return;
    }

    try {
      const parsed = parseRowJsonText(jsonText, editableColumns);
      form.reset({ ...form.state.values, ...parsed });
      setJsonError(null);
      setSubmitError(null);
      setViewMode("form");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Invalid JSON";
      setJsonError(message);
    }
  };

  const saveMutation = useMutation({
    meta: rowMutationMeta,
    mutationFn: async () => {
      setSubmitError(null);
      let value = form.state.values;
      if (viewMode === "json") {
        value = parseRowJsonText(jsonText, editableColumns);
        form.reset({ ...form.state.values, ...value });
      }
      const prepared = prepareSubmitValues(mode, columnMetadata, value, row);
      if (mode === "edit") {
        if (!prepared.primaryKey || Object.keys(prepared.primaryKey).length === 0) {
          throw new Error("Cannot update a row without a primary key");
        }
        return updateRowServerFn({
          data: {
            url: connectionUrl,
            schema,
            table,
            primaryKey: prepared.primaryKey as Record<
              string,
              string | number | boolean | null | undefined
            >,
            values: prepared.values as Record<string, string | number | boolean | null | undefined>,
          },
        });
      }
      return insertRowServerFn({
        data: {
          url: connectionUrl,
          schema,
          table,
          values: prepared.values as Record<string, string | number | boolean | null | undefined>,
        },
      });
    },
    onSuccess: () => {
      invalidateRowsQueries(queryClient);
      toaster.create({
        title: "Success",
        description:
          mode === "edit"
            ? "Row updated"
            : mode === "duplicate"
              ? "Row duplicated"
              : "Row inserted",
        type: "success",
      });
      onOpenChange(false);
    },
    onError: (error) => {
      const message = formatDbError(error);
      setSubmitError(message);
      toaster.create({
        title: "Could not save row",
        description: message,
        type: "error",
      });
    },
  });

  const title = mode === "edit" ? `Edit row` : mode === "duplicate" ? `Duplicate row` : `Add row`;

  return (
    <Sheet open={open} onOpenChange={(details) => onOpenChange(details.open)}>
      <SheetContent side="right" size="md" className="flex flex-col" data-testid="row-editor-sheet">
        <SheetHeader>
          <SheetTitle>
            {title} — {schema ? `${schema}.` : ""}
            {table}
          </SheetTitle>
          <SheetDescription>
            {mode === "edit"
              ? "Update column values and save. Primary key columns are read-only."
              : "Fill in column values. Leave auto-generated columns on Default."}
          </SheetDescription>
        </SheetHeader>

        {mode === "edit" && !hasPrimaryKey(columnMetadata) ? (
          <div
            className="border-border bg-muted/40 mx-4 rounded-md border px-3 py-3 text-sm"
            data-testid="row-editor-no-pk"
          >
            <p className="font-medium">Editing requires a primary key</p>
            <p className="text-muted-foreground mt-1 text-xs">
              This table has no primary key, so rows cannot be updated safely. Use{" "}
              <span className="font-medium">Add row</span> to insert, or add a primary key in the
              database schema.
            </p>
          </div>
        ) : !canEdit ? (
          <div className="text-muted-foreground px-4 text-sm">
            This table has no primary key, so rows cannot be edited. You can still insert new rows.
          </div>
        ) : (
          <form
            className="flex min-h-0 flex-1 flex-col"
            onSubmit={(e) => {
              e.preventDefault();
              e.stopPropagation();
              if (viewMode === "json") {
                try {
                  parseRowJsonText(jsonText, editableColumns);
                  setJsonError(null);
                } catch (error) {
                  const message = error instanceof Error ? error.message : "Invalid JSON";
                  setJsonError(message);
                  setSubmitError(message);
                  return;
                }
              }
              saveMutation.mutate();
            }}
          >
            <div className="px-4 pb-2">
              <Tabs
                value={viewMode}
                onValueChange={(details) => switchViewMode(details.value as EditorViewMode)}
              >
                <TabsList data-testid="row-editor-view-mode">
                  <TabsTrigger value="form">Form</TabsTrigger>
                  <TabsTrigger value="json">JSON</TabsTrigger>
                </TabsList>
              </Tabs>
            </div>

            <div className="flex-1 space-y-4 overflow-y-auto px-4 pb-2">
              {viewMode === "form" ? (
                editableColumns.map((column) => (
                  <form.Field key={column.name} name={column.name}>
                    {(field) => {
                      const canOmitDefault =
                        (mode === "insert" || mode === "duplicate") &&
                        (isAutoGeneratedColumn(column.dataType, column.defaultValue) ||
                          column.defaultValue != null ||
                          column.primaryKey);

                      return (
                        <ColumnInput
                          column={column}
                          value={field.state.value}
                          connectionUrl={connectionUrl}
                          disabled={
                            saveMutation.isPending || (mode === "edit" && column.primaryKey)
                          }
                          omitted={field.state.value === undefined}
                          onOmittedChange={
                            canOmitDefault
                              ? (omitted) => {
                                  field.handleChange(
                                    omitted
                                      ? undefined
                                      : column.nullable
                                        ? null
                                        : isAutoGeneratedColumn(
                                              column.dataType,
                                              column.defaultValue,
                                            )
                                          ? ""
                                          : "",
                                  );
                                }
                              : undefined
                          }
                          onChange={(next) => field.handleChange(next)}
                        />
                      );
                    }}
                  </form.Field>
                ))
              ) : (
                <div className="flex flex-col gap-2">
                  <JsonMonacoEditor
                    value={jsonText}
                    disabled={saveMutation.isPending}
                    height={420}
                    onChange={(next) => {
                      setJsonText(next);
                      setJsonError(null);
                    }}
                  />
                  {jsonError && (
                    <p className="text-destructive text-xs" data-testid="row-editor-json-error">
                      {jsonError}
                    </p>
                  )}
                </div>
              )}
            </div>

            <SheetFooter className="border-t">
              {submitError && (
                <div
                  className="border-destructive/40 bg-destructive/10 text-destructive rounded-md border px-3 py-2 text-xs"
                  data-testid="row-editor-error"
                >
                  {submitError}
                </div>
              )}
              <form.Subscribe selector={(state) => state.values}>
                {(values) => {
                  const activeValues =
                    viewMode === "json"
                      ? (() => {
                          try {
                            return parseRowJsonText(jsonText, editableColumns);
                          } catch {
                            return values;
                          }
                        })()
                      : values;
                  const prepared = prepareSubmitValues(mode, columnMetadata, activeValues, row);
                  const sqlPreview =
                    mode === "edit" && prepared.primaryKey
                      ? previewUpdateSql(schema, table, prepared.primaryKey, prepared.values)
                      : previewInsertSql(schema, table, prepared.values);

                  return (
                    <>
                      <Button
                        type="button"
                        variant="ghost"
                        size="sm"
                        className="self-start"
                        onClick={() => setShowSql((v) => !v)}
                      >
                        {showSql ? "Hide SQL" : "Show SQL"}
                      </Button>
                      {showSql && (
                        <pre
                          className="bg-muted max-h-40 overflow-auto rounded-md p-3 font-mono text-xs whitespace-pre-wrap"
                          data-testid="row-editor-sql-preview"
                        >
                          {sqlPreview}
                        </pre>
                      )}
                      <div className="flex justify-end gap-2">
                        <Button
                          type="button"
                          variant="outline"
                          onClick={() => onOpenChange(false)}
                          disabled={saveMutation.isPending}
                        >
                          Cancel
                        </Button>
                        <Button
                          type="submit"
                          disabled={saveMutation.isPending || !canEdit}
                          data-testid="row-editor-save"
                        >
                          {saveMutation.isPending ? "Saving…" : "Save"}
                        </Button>
                      </div>
                    </>
                  );
                }}
              </form.Subscribe>
            </SheetFooter>
          </form>
        )}
      </SheetContent>
    </Sheet>
  );
}

export function createClosedRowEditorState(): RowEditorSheetState {
  return { open: false, mode: "insert", row: null };
}
