import type { TableColumnMetadata } from "#src/server/introspection/introspection.ts";

import { Button } from "#src/components/ui/button.tsx";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
} from "#src/components/ui/sheet.tsx";
import { toaster } from "#src/components/ui/toaster.tsx";
import { isAutoGeneratedColumn } from "#src/lib/data-type-utils.ts";
import { formatDbError } from "#src/lib/format-db-error.ts";
import { insertRowServerFn } from "#src/server/introspection/start-fns/insert-row.start.ts";
import { updateRowServerFn } from "#src/server/introspection/start-fns/update-row.start.ts";
import { useForm } from "@tanstack/react-form";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";

import { ColumnInput } from "./column-input.tsx";
import { previewInsertSql, previewUpdateSql } from "./preview-sql.ts";
import {
  buildInitialRowValues,
  getEditableColumns,
  hasPrimaryKey,
  prepareSubmitValues,
  type RowEditorMode,
} from "./row-editor-values.ts";

export interface RowEditorSheetState {
  open: boolean;
  mode: RowEditorMode;
  row?: Record<string, unknown> | null;
}

export interface RowEditorSheetProps {
  open: boolean;
  mode: RowEditorMode;
  row?: Record<string, unknown> | null;
  connectionUrl: string;
  schema: string;
  table: string;
  columnMetadata: Array<TableColumnMetadata>;
  onOpenChange: (open: boolean) => void;
}

export function RowEditorSheet(props: RowEditorSheetProps) {
  const { open, mode, row, connectionUrl, schema, table, columnMetadata, onOpenChange } = props;

  const queryClient = useQueryClient();
  const [showSql, setShowSql] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const formKey = `${mode}:${table}:${row ? JSON.stringify(Object.keys(row)) : "new"}:${open}`;

  const initialValues = useMemo(
    () => buildInitialRowValues(mode, columnMetadata, row),
    [mode, columnMetadata, row],
  );

  const editableColumns = useMemo(
    () => getEditableColumns(mode, columnMetadata),
    [mode, columnMetadata],
  );

  const canEdit = mode === "insert" || mode === "duplicate" || hasPrimaryKey(columnMetadata);

  const form = useForm({
    defaultValues: initialValues,
  });

  // Reset form when sheet opens with new data
  useEffect(() => {
    if (open) {
      form.reset(initialValues);
      setShowSql(false);
      setSubmitError(null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- reset only on open/mode/row change
  }, [open, formKey]);

  const saveMutation = useMutation({
    mutationFn: async () => {
      setSubmitError(null);
      const value = form.state.values;
      const prepared = prepareSubmitValues(mode, columnMetadata, value, row);
      if (mode === "edit") {
        if (!prepared.primaryKey || Object.keys(prepared.primaryKey).length === 0) {
          throw new Error("Cannot update a row without a primary key");
        }
        return updateRowServerFn({
          data: {
            url: connectionUrl,
            schema,
            table,
            primaryKey: prepared.primaryKey as Record<
              string,
              string | number | boolean | null | undefined
            >,
            values: prepared.values as Record<string, string | number | boolean | null | undefined>,
          },
        });
      }
      return insertRowServerFn({
        data: {
          url: connectionUrl,
          schema,
          table,
          values: prepared.values as Record<string, string | number | boolean | null | undefined>,
        },
      });
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ["remote", "rows"] });
      toaster.create({
        title: "Success",
        description:
          mode === "edit"
            ? "Row updated"
            : mode === "duplicate"
              ? "Row duplicated"
              : "Row inserted",
        type: "success",
      });
      onOpenChange(false);
    },
    onError: (error) => {
      const message = formatDbError(error);
      setSubmitError(message);
      toaster.create({
        title: "Could not save row",
        description: message,
        type: "error",
      });
    },
  });

  const title = mode === "edit" ? `Edit row` : mode === "duplicate" ? `Duplicate row` : `Add row`;

  return (
    <Sheet open={open} onOpenChange={(details) => onOpenChange(details.open)}>
      <SheetContent side="right" size="md" className="flex flex-col" data-testid="row-editor-sheet">
        <SheetHeader>
          <SheetTitle>
            {title} — {schema ? `${schema}.` : ""}
            {table}
          </SheetTitle>
          <SheetDescription>
            {mode === "edit"
              ? "Update column values and save. Primary key columns are read-only."
              : "Fill in column values. Leave auto-generated columns on Default."}
          </SheetDescription>
        </SheetHeader>

        {mode === "edit" && !hasPrimaryKey(columnMetadata) ? (
          <div
            className="border-border bg-muted/40 mx-4 rounded-md border px-3 py-3 text-sm"
            data-testid="row-editor-no-pk"
          >
            <p className="font-medium">Editing requires a primary key</p>
            <p className="text-muted-foreground mt-1 text-xs">
              This table has no primary key, so rows cannot be updated safely. Use{" "}
              <span className="font-medium">Add row</span> to insert, or add a primary key in the
              database schema.
            </p>
          </div>
        ) : !canEdit ? (
          <div className="text-muted-foreground px-4 text-sm">
            This table has no primary key, so rows cannot be edited. You can still insert new rows.
          </div>
        ) : (
          <form
            className="flex min-h-0 flex-1 flex-col"
            onSubmit={(e) => {
              e.preventDefault();
              e.stopPropagation();
              saveMutation.mutate();
            }}
          >
            <div className="flex-1 space-y-4 overflow-y-auto px-4 pb-2">
              {editableColumns.map((column) => (
                <form.Field key={column.name} name={column.name}>
                  {(field) => {
                    const canOmitDefault =
                      (mode === "insert" || mode === "duplicate") &&
                      (isAutoGeneratedColumn(column.dataType, column.defaultValue) ||
                        column.defaultValue != null ||
                        column.primaryKey);

                    return (
                      <ColumnInput
                        column={column}
                        value={field.state.value}
                        connectionUrl={connectionUrl}
                        disabled={saveMutation.isPending || (mode === "edit" && column.primaryKey)}
                        omitted={field.state.value === undefined}
                        onOmittedChange={
                          canOmitDefault
                            ? (omitted) => {
                                field.handleChange(
                                  omitted
                                    ? undefined
                                    : column.nullable
                                      ? null
                                      : isAutoGeneratedColumn(column.dataType, column.defaultValue)
                                        ? ""
                                        : "",
                                );
                              }
                            : undefined
                        }
                        onChange={(next) => field.handleChange(next)}
                      />
                    );
                  }}
                </form.Field>
              ))}
            </div>

            <SheetFooter className="border-t">
              {submitError && (
                <div
                  className="border-destructive/40 bg-destructive/10 text-destructive rounded-md border px-3 py-2 text-xs"
                  data-testid="row-editor-error"
                >
                  {submitError}
                </div>
              )}
              <form.Subscribe selector={(state) => state.values}>
                {(values) => {
                  const prepared = prepareSubmitValues(mode, columnMetadata, values, row);
                  const sqlPreview =
                    mode === "edit" && prepared.primaryKey
                      ? previewUpdateSql(schema, table, prepared.primaryKey, prepared.values)
                      : previewInsertSql(schema, table, prepared.values);

                  return (
                    <>
                      <Button
                        type="button"
                        variant="ghost"
                        size="sm"
                        className="self-start"
                        onClick={() => setShowSql((v) => !v)}
                      >
                        {showSql ? "Hide SQL" : "Show SQL"}
                      </Button>
                      {showSql && (
                        <pre
                          className="bg-muted max-h-40 overflow-auto rounded-md p-3 font-mono text-xs whitespace-pre-wrap"
                          data-testid="row-editor-sql-preview"
                        >
                          {sqlPreview}
                        </pre>
                      )}
                      <div className="flex justify-end gap-2">
                        <Button
                          type="button"
                          variant="outline"
                          onClick={() => onOpenChange(false)}
                          disabled={saveMutation.isPending}
                        >
                          Cancel
                        </Button>
                        <Button
                          type="submit"
                          disabled={saveMutation.isPending || !canEdit}
                          data-testid="row-editor-save"
                        >
                          {saveMutation.isPending ? "Saving…" : "Save"}
                        </Button>
                      </div>
                    </>
                  );
                }}
              </form.Subscribe>
            </SheetFooter>
          </form>
        )}
      </SheetContent>
    </Sheet>
  );
}

export function createClosedRowEditorState(): RowEditorSheetState {
  return { open: false, mode: "insert", row: null };
}
