import type { TableColumnMetadata } from "#src/server/introspection/introspection.ts";

import {
  coerceColumnValue,
  isAutoGeneratedColumn,
  isBooleanDataType,
  isJsonDataType,
} from "#src/lib/data-type-utils.ts";
import { DADABASE_ROW_ID } from "#src/server/introspection/fns/row-identity.ts";

export type RowEditorMode = "insert" | "edit" | "duplicate";

export function getPrimaryKeyColumns(
  columnMetadata: ReadonlyArray<TableColumnMetadata>,
): Array<TableColumnMetadata> {
  return columnMetadata.filter((col) => col.primaryKey);
}

export function hasPrimaryKey(columnMetadata: ReadonlyArray<TableColumnMetadata>): boolean {
  return getPrimaryKeyColumns(columnMetadata).length > 0;
}

export function hasSystemRowIdentity(row?: Record<string, unknown> | null): boolean {
  return row != null && row[DADABASE_ROW_ID] != null;
}

/** True when the row can be uniquely targeted for update/delete. */
export function canLocateRow(
  columnMetadata: ReadonlyArray<TableColumnMetadata>,
  row?: Record<string, unknown> | null,
): boolean {
  return hasPrimaryKey(columnMetadata) || hasSystemRowIdentity(row);
}

export function extractPrimaryKeyValues(
  columnMetadata: ReadonlyArray<TableColumnMetadata>,
  row: Record<string, unknown>,
): Record<string, unknown> {
  const pkColumns = getPrimaryKeyColumns(columnMetadata);
  if (pkColumns.length > 0) {
    const pk: Record<string, unknown> = {};
    for (const col of pkColumns) {
      pk[col.name] = row[col.name] ?? null;
    }
    return pk;
  }

  if (hasSystemRowIdentity(row)) {
    return { [DADABASE_ROW_ID]: row[DADABASE_ROW_ID] };
  }

  return {};
}

function parseDefaultValue(column: TableColumnMetadata): unknown {
  const raw = column.defaultValue;
  if (raw == null) {
    return column.nullable ? null : isBooleanDataType(column.dataType) ? false : "";
  }

  const trimmed = raw.trim();
  if (trimmed.toLowerCase() === "null") return null;
  if (isBooleanDataType(column.dataType)) {
    return trimmed.toLowerCase() === "true" || trimmed === "1" || trimmed.toLowerCase() === "t";
  }

  // Strip PG type casts / quotes: 'foo'::text, nextval(...), etc.
  if (trimmed.includes("nextval(") || isAutoGeneratedColumn(column.dataType, raw)) {
    return undefined;
  }

  const quoted = trimmed.match(/^'(.*)'(?:::.*)?$/s);
  if (quoted) {
    return quoted[1].replace(/''/g, "'");
  }

  return trimmed;
}

function formatValueForInput(column: TableColumnMetadata, value: unknown): unknown {
  if (value === null || value === undefined) {
    return null;
  }
  if (isJsonDataType(column.dataType)) {
    if (typeof value === "string") return value;
    try {
      return JSON.stringify(value, null, 2);
    } catch {
      return String(value);
    }
  }
  if (value instanceof Date) {
    return value.toISOString();
  }
  return value;
}

/**
 * Build initial form values for insert / edit / duplicate modes.
 * `undefined` means "omit from INSERT" (use DB default / serial).
 */
export function buildInitialRowValues(
  mode: RowEditorMode,
  columnMetadata: ReadonlyArray<TableColumnMetadata>,
  row?: Record<string, unknown> | null,
): Record<string, unknown> {
  const values: Record<string, unknown> = {};

  for (const column of columnMetadata) {
    const auto = isAutoGeneratedColumn(column.dataType, column.defaultValue);

    if (mode === "insert") {
      if (auto) {
        values[column.name] = undefined;
      } else {
        values[column.name] = parseDefaultValue(column);
      }
      continue;
    }

    const fromRow = row?.[column.name];
    if (mode === "duplicate" && (auto || column.primaryKey)) {
      values[column.name] = undefined;
      continue;
    }

    values[column.name] = formatValueForInput(column, fromRow);
  }

  return values;
}

/**
 * Prepare values for the server: coerce types, drop omitted insert fields,
 * and (for update) exclude PK columns from the SET clause.
 */
export function prepareSubmitValues(
  mode: RowEditorMode,
  columnMetadata: ReadonlyArray<TableColumnMetadata>,
  formValues: Record<string, unknown>,
  originalRow?: Record<string, unknown> | null,
): {
  values: Record<string, unknown>;
  primaryKey?: Record<string, unknown>;
} {
  const values: Record<string, unknown> = {};

  for (const column of columnMetadata) {
    const raw = formValues[column.name];
    if (raw === undefined) {
      continue;
    }

    if (mode === "edit" && column.primaryKey) {
      continue;
    }

    values[column.name] = coerceColumnValue(column.dataType, raw);
  }

  if (mode === "edit") {
    return {
      values,
      primaryKey: extractPrimaryKeyValues(columnMetadata, originalRow ?? formValues),
    };
  }

  return { values };
}

export function getEditableColumns(
  mode: RowEditorMode,
  columnMetadata: ReadonlyArray<TableColumnMetadata>,
): Array<TableColumnMetadata> {
  if (mode === "edit") {
    return columnMetadata.filter((col) => !col.primaryKey);
  }
  return [...columnMetadata];
}
